// Mocks generated by Mockito 5.0.17 from annotations
// in rent_ready_app/test/data/remote/remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:aad_oauth/aad_oauth.dart' as _i4;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rent_ready_app/data/aadouth/aadouth_client.dart' as _i7;
import 'package:rent_ready_app/data/client/rest_client.dart' as _i5;
import 'package:rent_ready_app/data/models/account_response_model.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAccountResponseModel_0 extends _i1.Fake
    implements _i2.AccountResponseModel {}

class _FakeGlobalKey_1<T extends _i3.State<_i3.StatefulWidget>> extends _i1.Fake
    implements _i3.GlobalKey<T> {}

class _FakeAadOAuth_2 extends _i1.Fake implements _i4.AadOAuth {}

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i5.RestClient {
  MockRestClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AccountResponseModel> getAccount() =>
      (super.noSuchMethod(Invocation.method(#getAccount, []),
              returnValue: Future<_i2.AccountResponseModel>.value(
                  _FakeAccountResponseModel_0()))
          as _i6.Future<_i2.AccountResponseModel>);
}

/// A class which mocks [AadouthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAadouthClient extends _i1.Mock implements _i7.AadouthClient {
  MockAadouthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GlobalKey<_i3.NavigatorState> get navigtorKey =>
      (super.noSuchMethod(Invocation.getter(#navigtorKey),
              returnValue: _FakeGlobalKey_1<_i3.NavigatorState>())
          as _i3.GlobalKey<_i3.NavigatorState>);
  @override
  _i4.AadOAuth get oauth => (super.noSuchMethod(Invocation.getter(#oauth),
      returnValue: _FakeAadOAuth_2()) as _i4.AadOAuth);
  @override
  _i6.Future<String?> login() =>
      (super.noSuchMethod(Invocation.method(#login, []),
          returnValue: Future<String?>.value()) as _i6.Future<String?>);
}
